plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.cameraviewer'
    compileSdk 36

    defaultConfig {
        applicationId 'com.example.cameraviewer'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.media3:media3-exoplayer:1.11.0'
    implementation 'androidx.media3:media3-exoplayer-rtsp:1.11.0'
    implementation 'androidx.media3:media3-ui:1.11.0'
}
